### ISSUE TITLE
Testimonial 

### ISSUE THREAD

**Issue by ritika728** [nisha331/flow_cycle1#100]
Hey @nisha331, I would like to open this issue under JWOC. The testimonial page is messed up. I would like to make the following changes:
- changing its structure by making it 1*3 (3 testimonials in a single row)
- making it responsive
![image](https://user-images.githubusercontent.com/91181981/223964254-fe0230e9-0000-4e90-be50-d25f9a150810.png)

**Comment by nisha331** [comment]
this  is some path related issue . u can work on it

**Comment by nisha331** [comment]
can I see the result
