### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by khushimarothi** [nisha331/flow_cycle1#106]
I want to improve responsiveness of about page
Please Assign under JWOC

**Comment by nisha331** [comment]
only about? u can work for othere pages aswell it needed

**Comment by khushimarothi** [comment]
Its not easy to fix responsiveness of all pages .  If you want me to do that please add a label according to that work

**Comment by khushimarothi** [comment]
I have fixed responsiveness of about page . will create a pr when you merge the pending one.
