### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by EmberTSeal** [nisha331/flow_cycle1#11]
Currently the site is not responsive and does not display properly on mobile.

**Comment by EmberTSeal** [comment]
I want to work on this, I am a contributor under JWOC.

**Comment by nisha331** [comment]
@EmberTSeal the site is being redesigned . so let wait for that, thn u can see if making it responsive is needed or not

**Comment by EmberTSeal** [comment]
All right, thank you for responding.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
As of now its not needed.
