### ISSUE TITLE
Testimonial on the home page

### ISSUE THREAD

**Issue by S-ishita** [nisha331/flow_cycle1#110]
Testimonial instead of having a different page should be visible on the home page itself.
I want to fix it . Please assign this issue to me under JWOC.

**Comment by nisha331** [comment]
> Testimonial instead of having a different page should be visible on the home page itself. I want to fix it . Please assign this issue to me under JWOC.

Yes this is needed .  But there is some work going on in testimonial section we can get back to the issue after that

**Comment by nisha331** [comment]
> Testimonial instead of having a different page should be visible on the home page itself. I want to fix it . Please assign this issue to me under JWOC.

ok

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
