### ISSUE TITLE
enhance the scrollbar

### ISSUE THREAD

**Issue by taniaban2712** [nisha331/flow_cycle1#116]

**Comment by taniaban2712** [comment]
the scrollbar needs to be enhanced. I want to work under JWOC.

**Comment by nisha331** [comment]
ok

**Comment by Tavish108** [comment]
it's important to note that the code may produce unexpected results if used in conjunction with other HTML or CSS code that conflicts with it. Also, make sure we have to  link the HTML document to the Poppins font using the Google Fonts API in the head section of your HTML file. 
Please assign me this .  I want to work under JWOC.

**Comment by Tavish108** [comment]
I have enhanced the scroll bar . Please assign me this I want to work under jwoc

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
