### ISSUE TITLE
changes to be made in the entire faq page

### ISSUE THREAD

**Issue by taniaban2712** [nisha331/flow_cycle1#123]
![image](https://user-images.githubusercontent.com/110692684/224508819-1acf1d02-87f6-461e-acf1-84caee1975df.png)
the entire page doesnt have the css and some html code is wrong. also the css page isnt in the correct folder.

**Comment by taniaban2712** [comment]
I want to work under JWOC

**Comment by nisha331** [comment]
folder structure has been coreected . u can work on the css

**Comment by Awesomeasma** [comment]
@nisha331 
I would like to work on this under JWOC
