### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by ritika728** [nisha331/flow_cycle1#124]
Hey @nisha331 , I would like to open this issue under JWOC. 
- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google
- after selecting a specific language, user will be able to :
  - again translate the page by choosing new language
  - showing the original language
  - turn off the translation for that site

I will add this feature in the navbar of all the pages. Kindly assign

**Comment by Prateek556** [comment]
I want to work in this under JWOC

**Comment by nisha331** [comment]
where do u want to use it?

**Comment by ritika728** [comment]
@nisha331 I can add it in parallel to the flow cycle icon in the navbar of all the pages

**Comment by nisha331** [comment]
> @nisha331 I can add it in parallel to the flow cycle icon in the navbar of all the pages

Is it very much required?
And i meant whatdo u what to traslate

**Comment by ritika728** [comment]
@nisha331 it is an extra feature which is implemented on many new websites these days to make the user experience even better. It will translate the entire page into the preferred language. And since this website has quite a good amount of text, this feature would be great if implemented. This is an example of a website on which I have already implemented this feature

https://user-images.githubusercontent.com/91181981/224786118-d80856a3-d452-4104-be87-e9d55756b903.mp4

**Comment by ritika728** [comment]
@nisha331 please let me know if i can work on this issue

**Comment by ritika728** [comment]
@nisha331 hey, can i work on this issue ?
