### ISSUE TITLE
Create Responsive Error Page

### ISSUE THREAD

**Issue by TuhinBanerjee31** [nisha331/flow_cycle1#125]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
can I have a proper description @TuhinBanerjee31

**Comment by TuhinBanerjee31** [comment]
Want to create a 404 error page for the website which will be displayed if the user visits any wrong page location. It will contain a responsive and tempting UI with a Go back to home button.

**Comment by nisha331** [comment]
ok
