### ISSUE TITLE
navagation through pages

### ISSUE THREAD

**Issue by SHYALI** [nisha331/flow_cycle1#13]
are you jwoc participant?  yes
issue: we are not able to navigate through pages before going to the home page.
can I resolve this issue?

**Comment by nisha331** [comment]
The designe will be finalised by tonight thn I will make the issues for this u can have a look then. @SHYALI

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
Not needed rightnow, as design has changed
