### ISSUE TITLE
Header Section Needs a Restructure

### ISSUE THREAD

**Issue by AnkitMajee** [nisha331/flow_cycle1#14]
A better header section with drop down menu and proper working links.

**Comment by AimanSh123** [comment]
I want to work on this issue under JWOC so please assign it to me

**Comment by mayurimahto** [comment]
I would like to work on this issue under JWOC.

**Comment by nisha331** [comment]
The designe will be finalised by tonight thn I will make the issues for this u can have a look then. @AimanSh123 @AnkitMajee @mayurimahto

**Comment by AnkitMajee** [comment]
Please finalise the design and deploy otherwise it will be hard for the Mentee to find issue , bugs and work upon it @nisha331

**Comment by nisha331** [comment]
Mentees are working on it .It will be done .

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Babunshil** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
@AnkitMajee create the header and footer .
https://user-images.githubusercontent.com/88769427/219367124-b06047fd-5104-4ac3-a54c-0573460b6ea9.png
follow this desgin

**Comment by nisha331** [comment]
@AnkitMajee r u working??

**Comment by AnkitMajee** [comment]
@nisha331 Yes I am Working On it and i want to know you want the header in this desgin
![image](https://user-images.githubusercontent.com/76817118/219431323-b3bd6781-dfcf-4f6e-9329-2a963baac89d.png)

**Comment by nisha331** [comment]
yes.. the calender and avatar icon is in the img folder .
if u need the color code contact who has made the design. issue #3 
@AnkitMajee

**Comment by AnkitMajee** [comment]
OK take that into consideration
i'll send you few demo header after making it @nisha331

**Comment by nisha331** [comment]
> OK take that into consideration i'll send you few demo header after making it @nisha331

ok

**Comment by AnkitMajee** [comment]
Please have a look 
## Header home page
![image](https://user-images.githubusercontent.com/76817118/219650234-4fbdc69b-8271-45ed-868b-2255cca82038.png)
## Footer home page
![image](https://user-images.githubusercontent.com/76817118/219650352-af8b284b-3fd4-417d-bf2e-a1a36720310a.png)

## About US page with pink theme
![image](https://user-images.githubusercontent.com/76817118/219657480-a80da460-e8ec-4012-b5b7-7c77160ab04a.png)

## Menstrual page without pink theme
![image](https://user-images.githubusercontent.com/76817118/219657599-cccb9417-bb5a-4f66-ba05-7375d5cb5b76.png)

**Comment by nisha331** [comment]
kindly make the header as the header design. . @AnkitMajee .. all this extra things are not needed .. sizing are not ok

**Comment by AnkitMajee** [comment]
I have made same as the design please have a look
## The toggle button is beside the girl icon
![image](https://user-images.githubusercontent.com/76817118/219845427-11c6fccf-60df-446a-af4b-e8997604ecb9.png)

**Comment by nisha331** [comment]
no need of that toggle button as of now. @AnkitMajee

**Comment by AnkitMajee** [comment]
Ok I m removing it and do you want the same header and footer in all .html files 
@nisha331

**Comment by nisha331** [comment]
> Ok I m removing it and do you want the same header and footer in all .html files @nisha331

Yes and see the design the navbar is quite thik in the design .. so kindly improve it

**Comment by AnkitMajee** [comment]
Yes its will look thick after the body is added as the header has no background color
