### ISSUE TITLE
add counter animation

### ISSUE THREAD

**Issue by S-ishita** [nisha331/flow_cycle1#142]
I want to add counter animation which will show the number of users of our website , people benefitted from our website etc...

- Will be added in homepage
- Will be responsive

Please assign this issue to me under JWOC
A reference is provided below..

https://user-images.githubusercontent.com/104543751/225074179-6dc73c18-28a6-4edd-90eb-727225b5ee4e.mp4

**Comment by nisha331** [comment]
How will u count the number?

**Comment by S-ishita** [comment]
That would estimated..like we can keep 500 users , 200 benefitted etc
Even the testimonials aren't real so can these figures be :)

**Comment by nisha331** [comment]
> That would estimated..like we can keep 500 users , 200 benefitted etc Even the testimonials aren't real so can these figures be :)

ahh ok
