### ISSUE TITLE
Bug: Correction of Date for current month

### ISSUE THREAD

**Issue by EmberTSeal** [nisha331/flow_cycle1#19]
When a date of present month is selected, the next date should be in the next month.
For eg: if current date is 11th Feb 2023, the next date should be 11th Match 2023. However, it currently shows 11th Feb.
![image](https://user-images.githubusercontent.com/116507582/219136706-4dcca252-0f1b-49a8-80b1-88aabe7bca68.png)

**Comment by EmberTSeal** [comment]
I would like to work on this issue if it's available to work on currently. I am a contributor under JWOC.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
This already in progress
