### ISSUE TITLE
Project Structure and some changes

### ISSUE THREAD

**Issue by utkarsh006** [nisha331/flow_cycle1#21]
- Restructuring the project files into a proper module so that the code in the repo looks good.
- Assign this issue to me under JWOC.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
Delete all images. and put new images ask it from who have designed issue #3 (the calendar icon , avatar icon, and the main image) @utkarsh006

**Comment by utkarsh006** [comment]
@nisha331 For that you have to merge that PR first and then allow me to work upon this issue.
