### ISSUE TITLE
Adding FAQ Section 

### ISSUE THREAD

**Issue by ArgyPorgy** [nisha331/flow_cycle1#24]
I want to add faq section like the other 3 sections and add it to the drop down list. Please assign this issue to me under jwoc @nisha331 thank you!

**Comment by nisha331** [comment]
Wht do u wish to put in FAQ? @ArgyPorgy

**Comment by ArgyPorgy** [comment]
As the name suggests, i wanna put the frequently asked questions about periods and pregnancy. For now thats what ive thought, will add more sections in future. @nisha331

**Comment by nisha331** [comment]
okh.. so donot add anything in the home page as of now..
just create faq.html and css.. connetn with the home page will be later as home page is being constructed.
@ArgyPorgy

**Comment by ArgyPorgy** [comment]
alright, thanks!

**Comment by ArgyPorgy** [comment]
btw ma'am @nisha331 could you please add the difficulty tag as well?

**Comment by nisha331** [comment]
> btw ma'am @nisha331 could you please add the difficulty tag as well?

I will see the work and add it dont worry
