### ISSUE TITLE
Adding JS for "log your periods" button

### ISSUE THREAD

**Issue by ayushanand308** [nisha331/flow_cycle1#28]
This method will predict when the user will have their next period and manipulate the DOM for results

**Comment by ayushanand308** [comment]
Please assign me this issue under JWOC

**Comment by nisha331** [comment]
@ayushanand308 wait for the new design to be implemented .. u can work on this then

**Comment by ayushanand308** [comment]
Alright.

**Comment by ayushanand308** [comment]
@nisha331 Should I work on it now?

**Comment by nisha331** [comment]
@ayushanand308  When u click on confirm it should change the text.
![Screenshot from 2023-02-21 00-13-32](https://user-images.githubusercontent.com/76838660/220180196-895078b1-e176-439a-843e-c8ebdf6d17ab.png)
Instead of upper one it should be like this
![image](https://user-images.githubusercontent.com/76838660/220180313-7d2b92c4-3538-43ed-8d73-694543f0ee5d.png)

**Comment by nisha331** [comment]
@ayushanand308 r u working on it?

**Comment by ayushanand308** [comment]
Yes I am.

**Comment by ayushanand308** [comment]
![image](https://user-images.githubusercontent.com/99035102/220618938-e010b611-c924-43f8-a369-30fe809060ac.png)

Just have to add "edit periods dates" button

**Comment by ayushanand308** [comment]
[screen-capture (2).webm](https://user-images.githubusercontent.com/99035102/220625823-10e7fd4e-09c7-4475-baed-119d6b402567.webm)

@nisha331 Is this OK? 
P.S.Calendar is not visible in recording but on website it is working fine.

**Comment by vatan-prakash** [comment]
I want to work on this issue under JWOC please assign it to me

**Comment by nisha331** [comment]
@ayushanand308 y am i unable to see the calendar in the screen recording ? way it that ways? I dont think so . Eles every thing is fine.

**Comment by ayushanand308** [comment]
Its only in the recording. On the webpage it is indeed working fine.

**Comment by ayushanand308** [comment]
@nisha331  I have made a PR. Can you review that?
