### ISSUE TITLE
Create a page which gives knowledge about ovulation 

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#29]
Its should contain all the info regarding ovulation , when , how , precautions (from a good souce and mention the souce at the end of the page ) 

Make sure to create ovulation.html and ovulation.css .. (put css file in css folder) . do not do anything on the home page ..

**Comment by Tushar-go** [comment]
i want to work on this issue please assign it to me under Jwoc

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC.

**Comment by nisha331** [comment]
@Tushar-go go ahead
