### ISSUE TITLE
Redesigning the Home page 

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#3]
![dess](https://user-images.githubusercontent.com/76838660/218420947-65be2115-033d-4ea3-b41c-fa71b2702437.jpg)

This is the design thought for the home page when the user first land on the website .
![flo1](https://user-images.githubusercontent.com/76838660/218425607-5ce2492b-34e9-4b25-bf35-e6ccb096aae2.jpg)

This is the design when the person has already entered the date .

If any one wants to redesign it , you can do it . This issue is open for all , the persn whose design is selected will be assigned the task and the points will be rewarded .

https://www.canva.com/design/DAEe_S8mFIU/YRkqcBvK72O7D4yYjN9KCA/edit?utm_content=DAEe_S8mFIU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

https://www.canva.com/design/DAFacgmiWg0/BS-clxkGD9TcFrplLlrujA/edit?utm_content=DAFacgmiWg0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton  

Here is the link ..
**Just copy and work on your own file  . Donot  change anything on the original one. ANYONE DOING SO WILL NOT BE ALLOWED TO WORK ON THIS PROJECT ANY FURTHER**
background colour code #dbc1b1

For all JWOC participants entries will be taken on and after 15th of feb. before that .

**Comment by Aditi-Dahiya** [comment]
Hello mentor,
I want to redesign the home page, please assign to me this issue.
Thank you.

**Comment by ghost** [comment]
I want to work on this issue under JWOC

**Comment by Code1705** [comment]
Hey! @nisha331 ... I am interested to contribute to redesign your home page  , kindly assign me this issue.

**Comment by PrachiSingh66** [comment]
I want to work on this issue under JWOC.

**Comment by Aditi-Dahiya** [comment]
Hello mentor,
I want to redesign the home page, please assign to me this issue under JWOC.
Thank you.

**Comment by nisha331** [comment]
Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above

**Comment by nisha331** [comment]
hey @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 @itsshahinhere i am just expecting a canva design here no code.. this issue is related to UI designing not coding

**Comment by Code1705** [comment]
@nisha331 perfectly ok, I understood your requirement , will work on it.

**Comment by Aditi-Dahiya** [comment]
@nisha331, i understood your expectation and am on it, thank you for clearing out.

**Comment by takshilaa** [comment]
Hi @nisha331 . I'm ready to work on the design part. Kindly assign me this issue

**Comment by AshutoshSingh2021** [comment]
Hello, I want to redesign the Home page. Kindly assign it to me.

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by takshilaa** [comment]
Hi @nisha331.
I want to redesign it. Can you please assign to me this issue?
Thank you.

**Comment by purbakundu** [comment]
i want to contribute

**Comment by purbakundu** [comment]
i want to contribute

**Comment by AgnishaDe** [comment]
I want to contribute in this project under JWOC

**Comment by ghost** [comment]
> Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above

![About](https://user-images.githubusercontent.com/88769427/218853723-9054c1d5-8774-449b-81be-5b53d0ca6bd9.png)
![About (2)](https://user-images.githubusercontent.com/88769427/218853877-e7d7b142-9c12-4361-9245-3c7b9939d052.png)


Canva Link: https://www.canva.com/design/DAFaktcisUE/e6LvJiG_bBxUFObhNQjDZg/edit?utm_content=DAFaktcisUE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Aditi-Dahiya** [comment]
> Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above

Hello mentor,
Following is my design.

Canva Link - https://www.canva.com/design/DAFamwfq-8k/ZRDVMms2B-y2JkGiGcusiA/view?utm_content=DAFamwfq-8k&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

<img width="899" alt="Screenshot 2023-02-15 at 9 11 48 AM" src="https://user-images.githubusercontent.com/110183713/218923963-a050eb32-d456-49a0-89d0-d35a319c1621.png">

<img width="900" alt="Screenshot 2023-02-15 at 11 33 15 AM" src="https://user-images.githubusercontent.com/110183713/218945818-775b0e63-3b5e-473e-9e87-8b3a58256320.png">

**Comment by nisha331** [comment]
@itsshahinhere there needs to be q place for explore aswell

**Comment by ghost** [comment]
> @itsshahinhere there needs to be q place for explore aswell

So explore more section is not related to Article ?

I thought explore more section and Article section are same.

If not, should i add explore more section at the bottom of page or can i remove About menu and add explore ?

**Comment by ghost** [comment]
> @itsshahinhere there needs to be q place for explore aswell

![About](https://user-images.githubusercontent.com/88769427/218974999-a49c0d4d-670e-4c33-a881-3cdf5ca19715.png)
![About (2)](https://user-images.githubusercontent.com/88769427/218975012-dca3e681-5174-4668-9b65-fc881914df43.png)

Does it need anymore changes ?

**Comment by nisha331** [comment]
Can we have the bg color as #dbc1b1
 and a proper division header and the explore more thing .. (may be white as before) . becz when i click on explore I expect a white bg page to come so if explore part is with white bg .

@itsshahinhere

**Comment by ghost** [comment]
> Can we have the bg color as #dbc1b1 and a proper division header and the explore more thing .. (may be white as before) . becz when i click on explore I expect a white bg page to come so if explore part is with white bg .
> 
> @itsshahinhere

![About](https://user-images.githubusercontent.com/88769427/219042640-49b99d8d-4c4f-4c3b-b9b1-5b031a3418bc.png)
![About (2)](https://user-images.githubusercontent.com/88769427/219042653-abf291f2-a3bd-4184-a22f-d40ac5c613c6.png)

@nisha331 Like this ?

**Comment by Aditi-Dahiya** [comment]
> > Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above
> 
> Hello mentor, Following is my design.
> 
> Canva Link - https://www.canva.com/design/DAFamwfq-8k/ZRDVMms2B-y2JkGiGcusiA/view?utm_content=DAFamwfq-8k&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> <img alt="Screenshot 2023-02-15 at 9 11 48 AM" width="899" src="https://user-images.githubusercontent.com/110183713/218923963-a050eb32-d456-49a0-89d0-d35a319c1621.png">
> 
> <img alt="Screenshot 2023-02-15 at 11 33 15 AM" width="900" src="https://user-images.githubusercontent.com/110183713/218945818-775b0e63-3b5e-473e-9e87-8b3a58256320.png">

@nisha331 is this upto the requirement?

**Comment by vamsikrishnarh7** [comment]
@nisha331 Here is my design : 
https://www.canva.com/design/DAFapVRROcc/PoAIE2GzDGLZXc5cjfiB_g/view?utm_content=DAFapVRROcc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Code1705** [comment]
> Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above

Canva Link for my designs:-
https://www.canva.com/design/DAFankq8GiU/nrfyHiQdBXIzpk-979p1GQ/edit?utm_content=DAFankq8GiU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

https://www.canva.com/design/DAFaps4skI4/yBOh-i3xXGqt5ZXdLaN1rg/edit?utm_content=DAFaps4skI4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Aditi-Dahiya** [comment]
> > Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above
> 
> Hello mentor, Following is my design.
> 
> Canva Link - https://www.canva.com/design/DAFamwfq-8k/ZRDVMms2B-y2JkGiGcusiA/view?utm_content=DAFamwfq-8k&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> <img alt="Screenshot 2023-02-15 at 9 11 48 AM" width="899" src="https://user-images.githubusercontent.com/110183713/218923963-a050eb32-d456-49a0-89d0-d35a319c1621.png">
> 
> <img alt="Screenshot 2023-02-15 at 11 33 15 AM" width="900" src="https://user-images.githubusercontent.com/110183713/218945818-775b0e63-3b5e-473e-9e87-8b3a58256320.png">

This is my second design as per the background color #dbc1b1
Canva Link - https://www.canva.com/design/DAFap17Z4Vo/kNwLSeHkX7NYc9SacoLM5w/view?utm_content=DAFap17Z4Vo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
<img width="901" alt="Screenshot 2023-02-15 at 9 26 52 PM" src="https://user-images.githubusercontent.com/110183713/219081280-85794cd7-fcbe-46a9-a84a-a0348fe3dd67.png">

<img width="899" alt="Screenshot 2023-02-15 at 9 27 06 PM" src="https://user-images.githubusercontent.com/110183713/219081317-b08b661a-419c-4963-aba2-53613f0cd571.png">

Please share points to be improved if any @nisha331 🙂

**Comment by Code1705** [comment]
hey @nisha331 you some changes in my design please tell , i would rectify it.

**Comment by nisha331** [comment]
> hey @nisha331 you some changes in my design please tell , i would rectify it.

where is the link or screensort

**Comment by Code1705** [comment]
> > Hello @ADITI-2003 @itsshahinhere @Code1705 @PrachiSingh66 create your design and post it here in the comment . who so ever's design is selected will be assigned this issue .. u have only 1 day .. follow the rules mentioned above
> 
> Canva Link for my designs:- https://www.canva.com/design/DAFankq8GiU/nrfyHiQdBXIzpk-979p1GQ/edit?utm_content=DAFankq8GiU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> https://www.canva.com/design/DAFaps4skI4/yBOh-i3xXGqt5ZXdLaN1rg/edit?utm_content=DAFaps4skI4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

These.are the links..

**Comment by nisha331** [comment]
Thank you @Code1705 @ADITI-2003 for your designs .. I will move forward with @itsshahinhere design .. @itsshahinhere I need some improvement we can sit and fix it in the evening .

**Comment by ghost** [comment]
> Thank you @Code1705 @ADITI-2003 for your designs .. I will move forward with @itsshahinhere design .. @itsshahinhere I need some improvement we can sit and fix it in the evening .

Ok sure!!

**Comment by ghost** [comment]
![About](https://user-images.githubusercontent.com/88769427/219367124-b06047fd-5104-4ac3-a54c-0573460b6ea9.png)
![About (2)](https://user-images.githubusercontent.com/88769427/219367136-203f7714-74c2-43d4-a1fe-c0c43391adb4.png)

https://www.canva.com/design/DAFaktcisUE/e6LvJiG_bBxUFObhNQjDZg/edit?utm_content=DAFaktcisUE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

@nisha331 Ok ?

**Comment by nisha331** [comment]
YES @itsshahinhere
