### ISSUE TITLE
Create a quiz 

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#30]
Ask propwr 10- 15 ques regading periods , and at the end .. u check if the person needs to visit the doct or if every thing is good with her health .
https://www.healthshots.com/quiz/answer-these-12-questions-to-know-just-how-normal-is-your-period/
some what like this

**Comment by vk20july** [comment]
@nisha331 mam can you give the tag of JWOC and put the difficulty
because I want to work on this issue under JWOC

**Comment by nisha331** [comment]
Start working on it .. make quiz.html and quiz.css . put css file in css folder @vk20july

**Comment by vk20july** [comment]
ok mam

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc

**Comment by vk20july** [comment]
@nisha331 mam can I get the time to work on this untill monday max to max
though most probably it will complete by tomorrow

**Comment by nisha331** [comment]
> @nisha331 mam can I get the time to work on this untill monday max to max though most probably it will complete by tomorrow

ok .. No issue
