### ISSUE TITLE
create testimonials

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#38]
![WhatsApp Image 2023-02-18 at 16 39 38](https://user-images.githubusercontent.com/76838660/219857108-7d595059-99ec-4ce9-a6e1-53fe1b05abc9.jpeg)

I want it some what like this .. there should be sliders on both side to move left and right.. to see more  testimonials

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
ok @Neha00011 go ahead. creat testimonial.html ans testimonial.css and place css in css folder
