### ISSUE TITLE
No way to navigate to other page

### ISSUE THREAD

**Issue by ritika728** [nisha331/flow_cycle1#42]
Hey, I would like to open this issue under JWOC. 
In the below images for example, there is no way to move from one page to another. This is the case in majority of the pages. I wish to provide an option to navigate in the navbar of all the pages
![p1](https://user-images.githubusercontent.com/91181981/219950192-3a52a747-75f0-4ed5-8384-13a756332d59.png)

![p2](https://user-images.githubusercontent.com/91181981/219950194-e31ea5be-fd46-47d1-b666-aa6a8d83ccb4.png)

![p3](https://user-images.githubusercontent.com/91181981/219950195-cc50b3de-eb9e-4f83-aea7-189efa1b7005.png)

**Comment by Awesomeasma** [comment]
I want to work on this issue under jwoc.

**Comment by ritika728** [comment]
@nisha331 can I work on this issue ?

**Comment by nisha331** [comment]
@ritika728 i will assign this to u but after few things are complete

**Comment by ritika728** [comment]
> @ritika728 i will assign this to u but after few things are complete

Okay sure!

**Comment by ritika728** [comment]
@nisha331 can i start working on it now ?

**Comment by ritika728** [comment]
@nisha331 can I work on this issue now ?
