### ISSUE TITLE
Update the favicon and logo

### ISSUE THREAD

**Issue by tmsagarofficial** [nisha331/flow_cycle1#46]
I wanted to let u know that updating the logo and existing favicon with that of the same logo would make the site and the tab opening the site more appealing .
How it looks now
<img width="52" alt="image" src="https://user-images.githubusercontent.com/110724849/220176598-201230f5-4062-4d5c-8237-bdb543962431.png">
<img width="294" alt="image" src="https://user-images.githubusercontent.com/110724849/220176639-82ff3f60-18b7-45de-83ae-bbcd806496f3.png">
Fixing this will make it look border less and more beautiful

Let e know if i could work on this under JWOC

**Comment by nisha331** [comment]
ok u can do it.

**Comment by tmsagarofficial** [comment]
Thanks  @nisha331 for assigning this issue and letting me work on it.
Check my `Pull Request #50 `  Pull Request #50
