### ISSUE TITLE
onclick task 

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#48]
I want the calendar to only appear when u click on " log the date " button.
![Screenshot from 2023-02-21 00-08-06](https://user-images.githubusercontent.com/76838660/220179554-830f9a62-fccf-49ca-933d-374d276ff2e9.png)
itt should appear like this at the begining
![image](https://user-images.githubusercontent.com/76838660/220179783-19141f63-8ef6-4557-a332-8434edc23a3b.png)

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
sure

**Comment by vk20july** [comment]
@nisha331 mam can you also tag the difficulty type

**Comment by vatan-prakash** [comment]
I want to work on this issue under JWOC please assign it to me
