### ISSUE TITLE
Adding Health Care section

### ISSUE THREAD

**Issue by Riya14-dangra** [nisha331/flow_cycle1#5]
@nisha331  can you please assign this issue to me under JWOC 2K23.I want to work on it.
Hope you allow me to work on this issue!!

here in this section I am going to add the information regarding the health care for girls & Womens during their menstrual cycle with well designed UI.

**Comment by nisha331** [comment]
Ok @Riya14-dangra   but just say me to assign u this task after 12:00 am tonight . becz at this moment your issue is not valid for jwoc.

**Comment by PrachiSingh66** [comment]
I want to work on this issue under JWOC so please assign it to me

**Comment by manya0210** [comment]
Hello ma'am ..I want to contribute to this issue under jwoc

**Comment by nisha331** [comment]
@PrachiSingh66 let the home page basic structure be made thn i will assign it to u . because I want all the things to come whn I click on explore . wait for the explore button to be created

**Comment by nisha331** [comment]
> I want to work on this issue under JWOC so please assign it to me

What would you want to add?

**Comment by PrachiSingh66** [comment]
I want to design it as user friendly with health care information related to menstrual cycle and some precautions for it in detailed manner for girls which should be clear and easy information for them to understand.

**Comment by nisha331** [comment]
@PrachiSingh66 I am thinking  to keep this issue on hold . lets see . if its need later

**Comment by PrachiSingh66** [comment]
> @PrachiSingh66 I am thinking to keep this issue on hold . lets see . if its need later

Ok

**Comment by PrachiSingh66** [comment]
But if you consider it later please recommend me I really want to contribute here and also please give suggestions to me as I am new learner and eager to learn from you mentor.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
you can make a page on  health care for girls & Womens during their menstrual cycle . It should be a new pg . health.html and health .css @Riya14-dangra @PrachiSingh66 . who is available

**Comment by AK-shat-JAIN** [comment]
Hi @nisha331 
I want to work on this you can assign this to me and mention your requirements I Can do that

**Comment by nisha331** [comment]
> you can make a page on health care for girls & Womens during their menstrual cycle . It should be a new pg . health.html and health .css 

@AK-shat-JAIN start working on it and follow the above mentioned things

**Comment by AK-shat-JAIN** [comment]
Hlo @nisha331 
Thanks, I will do this

**Comment by AK-shat-JAIN** [comment]
Hlo @nisha331 
Please review my PR for this
