### ISSUE TITLE
Explore more.

### ISSUE THREAD

**Issue by khushimarothi** [nisha331/flow_cycle1#52]
Want to add a faq section on the landing page.
please assign it under jwoc

**Comment by nisha331** [comment]
Add all the things like faq, quiz, etc below the footer in this format  .. 
![Screenshot from 2023-02-21 19-08-48](https://user-images.githubusercontent.com/76838660/220360769-f8f08d5b-9a48-4bf1-88db-b5a582dc1b13.png)

**Comment by khushimarothi** [comment]
I am not able to locate the footer exactly. can you share ss where exactly you want me to create it.

**Comment by nisha331** [comment]
i want it in the home page itself..

**Comment by khushimarothi** [comment]
Okayy

**Comment by khushimarothi** [comment]
Please check discord.

**Comment by khushimarothi** [comment]
check discord !! @nisha331
