### ISSUE TITLE
[ESSENTIAL]: add Live website link

### ISSUE THREAD

**Issue by devvsakib** [nisha331/flow_cycle1#58]
This project has no live preview link. 

**To Reproduce**
Set up GitHub page for the live website.
Add the link to Readme file and about section.

**Comment by VaibhavTalkhande** [comment]
can is work on it under Jwoc

**Comment by Harry629** [comment]
I would like to work on this issue under JWOC.

**Comment by nisha331** [comment]
@devvsakib you can do it .

**Comment by devvsakib** [comment]
@nisha331  
I mean only you can add site link here 
![image](https://user-images.githubusercontent.com/88339569/220876017-53f96d0e-19f4-41c6-be09-7ff125e1b5a9.png)

**Comment by nisha331** [comment]
oh sorry .. I mixed up few issues .. then I dont think this isssue is required
