### ISSUE TITLE
[Enhancement] Improving the UI of the webpage

### ISSUE THREAD

**Issue by pooranjoyb** [nisha331/flow_cycle1#59]
# Reason/Context

## Why we need this improvement?
The current UI of the webpage is kinda unattractive. As because this is a healthcare website for educational purposes, it must be appealing to the users.

## How will this change help?
It will enhance the UI of the webpage. Hence giving a better user-experience.

# Description

## What changes have to be introduced?
Some significant CSS changes have to made in order to give this website a professional look.

## Will this be a breaking change?
No, it will not break any change, but will improve the current UI of the webpage.

## How could it be implemented/designed?
This can be achieved by the following : 
- Adding responsive navbar
- Creating a footer
- Styling Accordions and other components 
- Adding some custom animations for better look
- Adding images and gifs
- Some relative links to other health websites

### I would like to work in this issue under JWOC 2023. Would be glad if you could assign  me this issue. Please add Medium or Hard label for this issue because this will take some time to finish :) 👍  @nisha331

**Comment by Harry629** [comment]
I would like to work on this issue under JWOC.

**Comment by nisha331** [comment]
@pooranjoyb at this moment i dont think navbar is needed becz i want the user to se all the things after she clicks on expore more .. other than that if u want to make any changes .. can u make a protype on canva so that I can see whether its required or not.. (u can add animation css changes can be done, font styling )

**Comment by pooranjoyb** [comment]
Okay Ma'am, I'll share the prototype within 6 hrs. @nisha331

**Comment by pooranjoyb** [comment]
## Here is the UI I'm planning to design

- This version will be mobile responsive with a hamburger menu
- The letters `Welcome to Flowcycle` will be animated using Typing Animation
- I haven't added `Log Your Period` section in the page as because this feature isn't working as of now in the development server but will surely add it with some JavaScript animations in another issue.

# Related Screenshot

![FlowCycle Prototype](https://user-images.githubusercontent.com/90945182/220980377-d63fd330-37a7-40ff-97ca-bfcd2e64c136.png)

## @nisha331 Please check if the UI is fine?

**Comment by nisha331** [comment]
Ahh sorry but its 2 cluttered and I just wanted the period date to be shown in the home page. @pooranjoyb

**Comment by pooranjoyb** [comment]
Should I close the issue, or you'd suggest some fixes? :( @nisha331

**Comment by nisha331** [comment]
> Should I close the issue, or you'd suggest some fixes? :( @nisha331

lets close it as of now
