### ISSUE TITLE
Bug report- period calculator

### ISSUE THREAD

**Issue by smitra0916** [nisha331/flow_cycle1#6]
Are you a JWOC participant?
yes. Sourasish Mitra

What happened?
Period Calculator returning wrong values.
Also not working on pressing Enter on keyboard.

![image](https://user-images.githubusercontent.com/89326604/218820641-48602bf5-9256-45ac-8e7b-42cf067a1b78.png)

**Comment by smitra0916** [comment]
@nisha331 
I accidentally submit this 15 mins before.
can u assign me now?

**Comment by nisha331** [comment]
Yes smitra you can work on it .

**Comment by rohhhit31** [comment]
I can also work on it.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC
