### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by khushimarothi** [nisha331/flow_cycle1#61]
Want to add a preloader
Please assign under jwoc

**Comment by nisha331** [comment]
okkkh

**Comment by nisha331** [comment]
@khushimarothi pre-loader not working can u plz fix it I will change the tag to medium

**Comment by khushimarothi** [comment]
Yes. Suree

**Comment by khushimarothi** [comment]
Just noticed that the preloader gif didn't got pushed, my bad. Will fix it by tomorrow. 
I guess no need to assign a new label. Was a minor error . Rest is on you.

**Comment by nisha331** [comment]
> Just noticed that the preloader gif didn't got pushed, my bad. Will fix it by tomorrow. I guess no need to assign a new label. Was a minor error . Rest is on you.

It was not push then fine no increase in label..
