### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by S-ishita** [nisha331/flow_cycle1#62]
A button at the bottom of the articles page which will enhance user experience

IMAGE1

![Screenshot from 2023-02-24 17-59-12](https://user-images.githubusercontent.com/104543751/221179384-8ecc1c83-1945-4d39-958e-de73203c8635.png)

IMAGE2

![Screenshot from 2023-02-24 17-59-16](https://user-images.githubusercontent.com/104543751/221179391-346556d5-eb43-4c70-b58e-635944df68ba.png)

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC.

**Comment by nisha331** [comment]
okhh
