### ISSUE TITLE
Fix navbar and homepage

### ISSUE THREAD

**Issue by S-ishita** [nisha331/flow_cycle1#64]
Navbar elements are not present and homepage consists of two confirm buttons ..i want to fix it

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC

**Comment by nisha331** [comment]
I don't need anything on the navbar .. I want that when a person clicks on explore more then it slides down and show all the pages like health, ovulatn etc(all present in the repo ) to be displaced like this . 
https://user-images.githubusercontent.com/73363765/123540257-b5fa2f00-d75b-11eb-8ef5-d73340e009e1.png

**Comment by nisha331** [comment]
If u wnat to do it I will assign it to u  @S-ishita

**Comment by S-ishita** [comment]
Yes please assign me under JWOC @nisha331
