### ISSUE TITLE
Changes in home page

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#65]
The  calendar and confirm button should appear only when u click on log the date. (*At this moment it is being displayed even before clicking the log the date button . And there are 2 confirm buttons. only 1 button is neeeded.
![Screenshot from 2023-02-28 01-44-28](https://user-images.githubusercontent.com/76838660/221673721-770cc688-069e-43d9-905c-6080630e91ce.png)
..
..
..
there is confirm button once u click on log the date without entering the date. THat not required. 
![Screenshot from 2023-02-28 01-44-40](https://user-images.githubusercontent.com/76838660/221676097-29fa0ff0-f2aa-4b25-a38a-f81d66799216.png)

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
@nisha331 mam though i have a question what's the difference between ```onclick task``` and this task

**Comment by nisha331** [comment]
> I want to work on this issue under JWOC @nisha331 mam though i have a question what's the difference between `onclick task` and this task

That issue was resolved but still there is a problem. I am assigning it to u

**Comment by vk20july** [comment]
Ok mam

**Comment by vk20july** [comment]
@nisha331 Mam but here in my local desktop

https://user-images.githubusercontent.com/71543332/221906497-a88873af-cef8-4ef6-907f-503face0c500.mp4

 it is working perfectly fine

**Comment by vk20july** [comment]
@nisha331 made a PR kindly review
