### ISSUE TITLE
Improve testimonials 

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#66]
It should be like this  

![Screenshot from 2023-02-28 02-16-13](https://user-images.githubusercontent.com/76838660/221681814-b56e457f-3aa8-401a-ac3e-7f42bd7bdd51.png)

You should have forward and backward in left and right .

**Comment by Neha00011** [comment]
I want to work on this issue under jwoc.

**Comment by nisha331** [comment]
Yes go ahead put it below explore part
