### ISSUE TITLE
improve design and look of all the pages

### ISSUE THREAD

**Issue by nisha331** [nisha331/flow_cycle1#67]
Use a single design for all the pages ovulatn, pregnancy, quiz, health etc.

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC @nisha331

**Comment by nisha331** [comment]
go Ahead @S-ishita

**Comment by S-ishita** [comment]
Please change the labels to hard..

**Comment by Awesomeasma** [comment]
@nisha331 
I would like to work on this issue under JWOC
