### ISSUE TITLE
Remove the shadow of images while drag and drop

### ISSUE THREAD

**Issue by utkarsh006** [nisha331/flow_cycle1#68]
- Assign this issue to me under JWOC
![Screenshot (360)](https://user-images.githubusercontent.com/94545831/221733778-01990584-348f-4794-9ee0-33dd32b225c6.png)
![Screenshot (361)](https://user-images.githubusercontent.com/94545831/221733786-78aa373f-0b4d-4824-bbd6-5aa345dda5b6.png)

**Comment by nisha331** [comment]
@utkarsh006 updates?

**Comment by utkarsh006** [comment]
@nisha331 Working on this issue since 3 days, and one thing to note that is, this ain't an easy issue. The links are coming under shadow when images don't. Can you tell me how to proceed ahead?

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC

**Comment by Prateek556** [comment]
I would like to work on this issue under JWOC
