### ISSUE TITLE
Improve The UI of Ovulation Page

### ISSUE THREAD

**Issue by psykat1116** [nisha331/flow_cycle1#71]
There is just basic design in ovulation page I want to work on this and improve the UI and the button to go back top is always visible i also want to fix this. Please Assign me to this to work under JWOC. 
![Screenshot 2023-02-28 232452](https://user-images.githubusercontent.com/95569573/221938037-964bf7d3-4b62-45ac-a49c-c80841dddb4f.png)

**Comment by nisha331** [comment]
#67 will solve this.
