### ISSUE TITLE
Error message is displaying at improper place thus making UI not so good looking

### ISSUE THREAD

**Issue by ManasaKaza** [nisha331/flow_cycle1#75]
I want to work on this issue under JWOC

**Comment by nisha331** [comment]
plz provide screen short of the issue u want to solve

**Comment by ManasaKaza** [comment]
![image](https://user-images.githubusercontent.com/122222373/222635513-6a338f7e-3c2c-4137-aeff-dade6337ae0d.png)
There, the alert message is not in the proper place

**Comment by nisha331** [comment]
Can u update the code . and see if its still required

**Comment by ManasaKaza** [comment]
> Can u update the code . and see if its still required

Nothing  start working  on  it

**Comment by khushimarothi** [comment]
I want to work on this under jwoc. or either I can improve complete page responsiveness in the issue created #80

**Comment by nisha331** [comment]
@ManasaKaza its already been days , I will have to assign it to @khushimarothi if its not done by tonight

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
