### ISSUE TITLE
I want to add hover effect on log the date Botton

### ISSUE THREAD

**Issue by Babunshil** [nisha331/flow_cycle1#78]
I want to add the hover effect because it improves the user experience a lot. Please assign me.

![This is an image](https://www.linkpicture.com/q/Screenshot-27_15.png)
![This is an image](https://www.linkpicture.com/q/Screenshot-25_5.png)

**Comment by nisha331** [comment]
lets not make it black .. Just invert the color of text and backgraound on howering

**Comment by Babunshil** [comment]
ok mam

**Comment by Babunshil** [comment]
@nisha331  mam like this ?
![this is an image](https://www.linkpicture.com/q/FLOW-CYCLE-Google-Chrome-3_4_2023-11_56_24-PM.png)
