### ISSUE TITLE
Exercises during periods

### ISSUE THREAD

**Issue by RishabhJain0721** [nisha331/flow_cycle1#8]
I want to design a section for all the exercises that a women can do during their menstrual cycle.
I shall be trying to achieve this using written content,images and video links to appropriate content.

**Comment by nisha331** [comment]
Ok  @RishabhJain0721 You can do it .. but dont add it anywhere in the home page create a separe html file so that later it can be encorporated in code base .. create ur exercise.htm excercise.css and work on it .

**Comment by RishabhJain0721** [comment]
Alright @nisha331

**Comment by RishabhJain0721** [comment]
Hi @nisha331 
I have created a PR. Could you please review that.

**Comment by nisha331** [comment]
done @RishabhJain0721
