### ISSUE TITLE
[Bug] Footer Breaks in smaller screens

### ISSUE THREAD

**Issue by pooranjoyb** [nisha331/flow_cycle1#83]
I have found that footer of `menstrualcycle.html` `pregnancy.html` and `womenhealth.html` pages breaks in smaller screen size. 
### Screenshots :

![ss](https://user-images.githubusercontent.com/90945182/222922875-69e8a627-0f8b-4173-a7fe-7f6605e04760.png)

Assign me this issue under JWOC '2023 @nisha331

**Comment by nisha331** [comment]
Footer is being changed at this moment . KIndly get back to the issue after that pr is merged
