### ISSUE TITLE
Create a Contact Us Page

### ISSUE THREAD

**Issue by khushimarothi** [nisha331/flow_cycle1#89]
I want to create a contact us page for the website
please assign under JWOC

**Comment by nisha331** [comment]
ok , but where do u want to place it?

**Comment by khushimarothi** [comment]
On the nav ? what say ? or either we can exceed the page ... place it below explore more section

**Comment by nisha331** [comment]
lets keep it in footer what say?
will lable it later start working on it

**Comment by khushimarothi** [comment]
Okay lets try.. I will make it responsive as well.

**Comment by khushimarothi** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/85816852/223925487-d036f775-2915-4351-898c-b45d9b21cbe4.png)

check this

**Comment by khushimarothi** [comment]
I noticed that the preloader gif was deleted. Pushing it back again...

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
