### ISSUE TITLE
[Enhancement] Folder Restructuring is needed

### ISSUE THREAD

**Issue by pooranjoyb** [nisha331/flow_cycle1#97]
## Issues : 
The folder structuring for the project is messed up as the directories are not organized properly.

## FIX : 
- [x] Need to use ```.gitignore``` to ignore some basic static files
- [x] Add a seperate ``src`` directory for the frontend. CSS, JS etc should be inside one ``src`` directory

Would be glad if you assign these issues to me under **JGEC Winter of Code**.  @nisha331

**Comment by nisha331** [comment]
ok
